Task 5 done
KatePodolsky/nodejs-homework-rest-api pull request #4
Opened 2021-09-14 14:42 UTC by KatePodolsky

2021-09-14 22:10 UTC, Danil44 requested changes

2021-09-14 22:10 UTC, Danil44 commented on controllers/users/avatars.js
> +const UpdateAvatar = async (req, res) => {
З великої літери ми називаємо лише класи

2021-09-14 22:11 UTC, Danil44 approved these changes

2021-09-14 22:11 UTC, Danil44 commented
Виправ комент і можеш мерджити

2021-09-16 04:44 UTC, KatePodolsky commented on controllers/users/avatars.js
> +const UpdateAvatar = async (req, res) => {
Добре, дякую.

2021-09-16 04:45 UTC, merged